- name: Install monitoring stack (Prometheus & Grafana)
  hosts: all
  become: yes
  tasks:
    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Download Grafana
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_9.0.0_amd64.deb
        dest: /tmp/grafana.deb

    - name: Install Grafana
      apt:
        deb: /tmp/grafana.deb